- builder:
    name: devstack-checkout
    builders:
      - shell: |
          #!/bin/bash -xe
          if [[ ! -e devstack-gate ]]; then
              git clone git://git.openstack.org/openstack-infra/devstack-gate
          else
              cd devstack-gate
              git remote set-url origin git://git.openstack.org/openstack-infra/devstack-gate
              git remote update
              git reset --hard
              if ! git clean -x -f ; then
                  sleep 1
                  git clean -x -f
              fi
              git checkout master
              git reset --hard remotes/origin/master
              if ! git clean -x -f ; then
                  sleep 1
                  git clean -x -f
              fi
              cd ..
          fi

- builder:
    name: devstack-checkout-http
    builders:
      - shell: |
          #!/bin/bash -xe
          if [[ ! -e devstack-gate ]]; then
              git clone http://git.openstack.org/openstack-infra/devstack-gate
          else
              cd devstack-gate
              git remote set-url origin http://git.openstack.org/openstack-infra/devstack-gate
              git remote update
              git reset --hard
              if ! git clean -x -f ; then
                  sleep 1
                  git clean -x -f
              fi
              git checkout master
              git reset --hard remotes/origin/master
              if ! git clean -x -f ; then
                  sleep 1
                  git clean -x -f
              fi
              cd ..
          fi

- builder:
    name: python-install-from-zuul
    builders:
      - shell: |
          #!/bin/bash -xe
          # Install the client from the patch
          git clone $ZUUL_URL/$ZUUL_PROJECT
          cd $ZUUL_PROJECT
          git fetch $ZUUL_URL/$ZUUL_PROJECT $ZUUL_REF

          sudo python setup.py install

- builder:
    name: openstack-pypi-setup
    builders:
      - shell: |
          #!/bin/bash -xe
          echo "Using pypi mirror http://pypi.python.org/openstack"
          cat <<EOF > ~/.pydistutils.cfg
          [easy_install]
          index_url = http://pypi.python.org/simple
          find_links = /var/cache/pip
          EOF

          cat <<EOF > ~/.pip/pip.conf
          [global]
          index-url = http://pypi.python.org/simple
          extra-index-url = http://pypi.python.org/simple
          find-links = /var/cache/pip
          timeout = 60
          EOF

- builder:
    name: link-logs
    builders:
      - shell: |
          #!/bin/sh
          echo "Triggered by: https://review.openstack.org/$ZUUL_CHANGE patchset $ZUUL_PATCHSET"

          echo "Detailed logs: http://127.0.0.1/$LOG_PATH/"

- publisher:
    name: console-log
    publishers:
      - scp:
          site: 'LogServer'
          files:
            - target: 'logs/$LOG_PATH'
              copy-console: true
              copy-after-failure: true

- publisher:
    name: devstack-logs
    publishers:
      - scp:
          site: 'LogServer'
          files:
            - target: 'logs/$LOG_PATH'
              source: 'logs/**'
              keep-hierarchy: true
              copy-after-failure: true

- publisher:
    name: devstack-logs-local
    publishers:
      - copy-to-master:
            includes:
              - 'logs/**'
            destination: '/tmp/$BUILD_TAG'

- builder:
    name: net-info
    builders:
      - shell: |
          #!/bin/sh
          export PATH=$PATH:/sbin
          echo "Network interface addresses..."
          ip address show
          echo "Network routing tables..."
          ip route show
          ip -6 route show
          echo "Network neighbors..."
          ip neighbor show
